name: Java CI with Maven (Patient Management System)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Show Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run tests
        run: mvn test --file pom.xml

      - name: Upload Executable JAR
        uses: actions/upload-artifact@v4
        with:
          name: Patient-Management-System-jar
          path: target/*.jar
